/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "text-main": "#15284E",
        "on-surface": "#1a1c1c",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "secondary": "#bb0014",
        "on-tertiary-container": "#90b2d1",
        "surface-container-lowest": "#ffffff",
        "attention-yellow": "#FACC15",
        "primary-fixed": "#e0e0ff",
        "surface-variant": "#e2e2e2",
        "on-secondary-fixed": "#410002",
        "surface-container": "#eeeeee",
        "secondary-fixed": "#ffdad6",
        "on-secondary-container": "#fffbff",
        "tertiary-fixed": "#cce5ff",
        "outline": "#767684",
        "secondary-fixed-dim": "#ffb4ab",
        "surface-tint": "#4952c0",
        "surface-container-low": "#f3f3f3",
        "surface-cream": "#FEFDF3",
        "on-primary-container": "#a1a8ff",
        "primary-fixed-dim": "#bec2ff",
        "on-error": "#ffffff",
        "on-background": "#1a1c1c",
        "on-error-container": "#93000a",
        "secondary-container": "#e51c23",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#3038a7",
        "heritage-red": "#8B0000",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#93000d",
        "outline-variant": "#c6c5d5",
        "inverse-primary": "#bec2ff",
        "surface-container-highest": "#e2e2e2",
        "inverse-on-surface": "#f1f1f1",
        "tertiary-fixed-dim": "#a8caea",
        "primary": "#0e158d",
        "inverse-surface": "#2f3131",
        "on-primary-fixed": "#00026c",
        "primary-container": "#2b33a2",
        "surface-container-high": "#e8e8e8",
        "tertiary-container": "#22455f",
        "error": "#ba1a1a",
        "surface": "#f9f9f9",
        "on-tertiary-fixed-variant": "#274a64",
        "background": "#f9f9f9",
        "surface-bright": "#f9f9f9",
        "on-surface-variant": "#454653",
        "on-tertiary-fixed": "#001e31",
        "tertiary": "#052f48",
        "surface-dim": "#dadada"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "unit": "8px",
        "stack-md": "16px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "container-max-width": "1280px"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Hanken Grotesk"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "body-sm": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "label-lg": ["Hanken Grotesk"],
        "headline-xl": ["Plus Jakarta Sans"],
        "price-display": ["Plus Jakarta Sans"],
        "body-md": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "14px", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "price-display": ["24px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
